In [ ]:
#numpy in python


In [ ]:
# install numpy in python
%pip install numpy

In [ ]:
# inport numpy in python
import numpy as np

# create a numpy array in python
a = np.array([11,12,13,14,15])
print(a)

[11 12 13 14 15]


In [ ]:
# access elements in numpy array in python
print(a[0])  # first element
print(a[1])  # second element

11
12


In [ ]:
# modify elements in numpys aaray in python
a[0] = 100
print(a)  # first element is modified to 100

[100  12  13  14  15]


In [ ]:
# cheking version of numpy in python
print(np.__version__)  # print version of numpy

2.0.2


In [ ]:
# create a numpy array with zeros in python
a = np.zeros((3,4)) # 3 rows and colums
print(a) # print numpy array with zeros

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# create 2nd numpy array in python
a = np.array ([[1,2,3,], [4,5,6], [7,8,9]]) # 3 rows and 3 columns
print (a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# create a 3d numpy array in python
a = np.array ([[[1,2], [3,4]], [[5,6],[7,8]]]) # 2 layers, 2 rows and 2 columns

print (a) # print 3d numpy array
print(a.shape)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [ ]:
# check the demensions of numpy76 array in python
print (a.ndim) # print number of dimensions of numpy array


3


In [ ]:
# Higher-Dimensional Arrays
# create a 4d numpy array in python
a = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]]])  # 1 layer, 2 rows and 2 columns
print(a) # print 4d numpy array
print(a.shape) # print shape of 4d numpy array


[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
(1, 2, 2, 2)


In [ ]:
# Ellipsis (...) Indexing
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_3d[...,0]) # Access the first element along the third dimension ([[1,3],[5,7]])


[[1 3]
 [5 7]]
