In [ ]:
20/02/25
#print () use
print ("Welcome to R_Programming")
print ("sahil gupta")
print (9892391043)

[1] "Welcome to R_Programming"
[1] "sahil gupta"
[1] 9892391043


In [ ]:
#cat ()
cat ("Wellcome To Borivali\n")
cat ("Wellcome To Keerti", 12345)
cat ("\nadd number",40+35)

Wellcome To Borivali
Wellcome To Keerti 12345
add number 75

In [ ]:
# variables
name <- "Sahil"
age <-22
height<-5.3

cat("My name is:",name)
cat ("\nMy age is:",age)
cat("\nMy height is:",height)

My name is: Sahil
My age is: 22
My height is: 5.3

In [ ]:
a<- 50
b<- 70
c <-a+b
cat ("result is:",c)

result is: 120

In [ ]:
a<-34
b<-56
c<-a-b
cat ("result is:",c)

e<-58
f<-95
g<-e*f
cat ("\nresult is:",g)

h<-69
i<-45
k<-h/i
cat ("\nreslut is:",k)

result is: -22
result is: 5510
reslut is: 1.533333

In [ ]:
25/2/25

# task :
# input
# Enter your name : Nishant
# Enter your roll number : A234A

# Enter Java Marks out of 100 : 56
# Enter C++ Marks out of 100 : 50
# Enter go Marks out of 100 : 60
# Enter python Marks out of 100 : 75
# Enter R Marks out of 100 : 23

# Total = ?
# per% = ?

In [ ]:
name <- "Nishant"
roll_number <-"A234A"

#paste()

student_information <- paste("Details :" ,name, roll_number)
print (student_information)



[1] "Details : Nishant A234A"


In [ ]:
#readline()

a <- as.integer(readline("Enter java marks out of 100  "))
b <- as.integer(readline("Enter C++ marks out of 100 "))
c <- as.integer(readline("Enter go marks out of 100 "))
d <- as.integer(readline("Enter python marks out of 100 "))
e <- as.integer(readline("Enter R marks out of 100 "))


result = (a+b+c+d+e)

cat ("\n Your result is :", result)


#presentage

#Presentage = result*100/500
#cat("\n Your presentage is:" , Presentage,"%")






In [ ]:
# 27 Feb 2025
# Operator
# Arithmetic Operators:

x<-555
y<-420
x+y
x-y
x*y
x%/%y
x%%y

25%%2


[1] 975

[1] 135

[1] 233100

[1] 1

[1] 135

[1] 1

In [ ]:
# Comparison Operators
55<35
555>345
45==45
46!=46
23<=23
23<=45
25>=25
20>=23

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

In [ ]:
# logical Operator
# and &

35 < 45 & 45 == 10
#  t    &    f
35 < 45 & 35 !=20

# OR |

  35<55 | 55 == 20

  # not !
  55!=55


[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

In [ ]:
# Assignment Operators
x<-10
print (x)

y = 20
print(y)

[1] 10
[1] 20


In [ ]:
data <- c(12,23,14,15,16,17)

12 %in% data

20 %in% data

[1] TRUE

[1] FALSE

In [ ]:
data = 21:30
data

[1] 21 22 23 24 25 26 27 28 29 30

In [ ]:
# R if..else
# find the smallest number
x <- 450
y <- 90
if(x<y)
{
  print("x is smallest value")
  #t
}else
{
  #f
  print("x is not smallest value")

}


[1] "x is not smallest value"


In [ ]:
#find odd and even number
x<-50

if(x%%2 == 0)
{
  print("x is an even number")
}else
{
  print ("x is an odd number")
}

[1] "x is an even number"


In [ ]:
# With AI code
# prompt: smallest or largest

#find the smallest number
x <- 450
y <- 90
if(x < y){
  print("x is the smallest value")
} else {
  print("y is the smallest value")
}

#find odd and even number
x <- 43
if(x %% 2 == 0){
  print("x is an even number")
} else {
  print("x is an odd number")
}

[1] "y is the smallest value"
[1] "x is an odd number"


In [ ]:
# Date : 1 March 2025

# nested if else

a <- 555
b <- 600
c <- 570
d <- 9

if(a < b & a < c & a < d ) {
  print ("a is smallest number")
}else if (b < a & b < c & b < d){
  print ("b is smallest number")
}else if(c < a & c < b & c < d){
  print("c is smallest number")
}else{
print ("d is smallest number")
}






[1] "d is smallest number"


In [ ]:
#1 to 20 odd or even looping

for (i in 1:20){
  if(i%%2 ){
    cat(i,"odd",'\n')
   } else{
      cat(i,"even",'\n')
    }
  }



1 odd 
2 even 
3 odd 
4 even 
5 odd 
6 even 
7 odd 
8 even 
9 odd 
10 even 
11 odd 
12 even 
13 odd 
14 even 
15 odd 
16 even 
17 odd 
18 even 
19 odd 
20 even 


In [ ]:
# prompt: odd or even in looping 1 to 20

for (a in 1:20){
  if(a %% 2 == 0){
    cat(a,"is even",'\n')
  } else{
    cat(a,"is odd",'\n')
  }
}

1 is odd 
2 is even 
3 is odd 
4 is even 
5 is odd 
6 is even 
7 is odd 
8 is even 
9 is odd 
10 is even 
11 is odd 
12 is even 
13 is odd 
14 is even 
15 is odd 
16 is even 
17 is odd 
18 is even 
19 is odd 
20 is even 


In [ ]:
# 4 March 2025
# while loop

# start point
# end point
# print/output
# 1,2,3,4.. / 4,3,2,1..

a <- 1
while (a <= 10){
  print (a)
  a <- a + 1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [ ]:
count <- 1
repeat {
  print ("Count:", count)
  count <- count + 1
  if (count > 5) {
    break
  }
  }

In [ ]:
for(i in 1:20){
  if(i > 5){
    break
  }else{
    print(i)
  }
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [ ]:
for(i in 1:20){
  if(i > 5){
    next
  }else{
    print(i)
  }
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [ ]:
# basic function
# function
# functionName <- function(){
#   task ....
# }

info <- function(){
  cat("\nWelcome to Codes with pankaj")
  cat("\nwelcome to cwpc")
}

# call the function
info()
info()


Welcome to Codes with pankaj
welcome to cwpc
Welcome to Codes with pankaj
welcome to cwpc

In [ ]:
# function with arg..

add <- function(number1,number2){
  result <- number1 + number2
  cat("\n Result <- ",result)
}

In [ ]:
add(124,456)
add(789,7000)


 Result <-  580
 Result <-  7789

In [ ]:
# bill

bill <- function(price,quantity,gst){
  total_amount <- price*quantity
  gst_amount <- total_amount*gst/100
  total_price <- total_amount+gst_amount

  cat("\n--------bill--------\n")
  cat("\nAmount = ",price,"/-")
  cat("\nquantity = ",price,"/-")
  cat("\nGST = ",gst,"%")
  cat("\nGST Amount  = ",gst_amount,"/-")
  cat("\nTotal Price (With GST)  = ",total_price,"/-")

}


In [ ]:
bill (578,5,12)


--------bill--------

Amount =  578 /-
GST =  12 %
GST Amount  =  346.8 /-
Total Price (With GST)  =  3236.8 /-

In [ ]:
# Date : 6 March 2025
# function with return
numbers <-function (){
  return (900)
}

# get return value
x <- numbers()
print (x)


[1] 900


In [ ]:
# function with return type with arg...

add <- function (num1,num2){
  result <- num1+num2
  return (result)
}

print(add(665,852))
print(add(40,50))

[1] 1517
[1] 90


In [ ]:
# string funtion
data1 <- "Sahil.R_Programming"
print (nchar(data1))

# Substring Extraction
substring(data1,3,15)

# String Manipulation
tolower(data1)

[1] 19


[1] "hil.R_Program"

[1] "sahil.r_programming"

In [ ]:
data1 <- "Orange"
data2 <- "Banana"
result <- data1>data2
print (result)

[1] TRUE


In [ ]:
# String interpolation
name <- "Sahil"
age <- 22
height <- 5.3
greeting <- sprintf("Hello, my name is %s and I am %s years old. and height %f",name, age,height)
cat("Greeting:", greeting,"\n")

print(greeting)

Greeting: Hello, my name is Sahil and I am 22 years old. and height 5.300000 
[1] "Hello, my name is Sahil and I am 22 years old. and height 5.300000"


In [ ]:
# Splitting and joining strings
text <- "apple,banana,cherry"
split_text <- strsplit(text,",")[[1]]
joined_text <- paste(split_text, collapse =" - ")
cat("Joined text:", joined_text,"\n")

Joined text: apple - banana - cherry 


In [ ]:
# R Vectors
data <- c('java','R','python','c++')

data
print(data)
cat(data)

[1] "java"   "R"      "python" "c++"

[1] "java"   "R"      "python" "c++"   
java R python c++

In [ ]:
#access data
data[2]
data[4]
data[1]
data[3]


[1] "R"

[1] "c++"

[1] "java"

[1] "python"

In [ ]:
# Date : 8 March 2025
data = c(178,654,258,852,159)

sum (data)
length(data)
mean(data)      #(mean means average.)
data^2

[1] 2101

[1] 5

[1] 420.2

[1]  31684 427716  66564 725904  25281

In [ ]:
# Matrix
numeric_matrix <-matrix(data = 21:29, nrow = 3,ncol = 3)
numeric_matrix

[,1] [,2] [,3]
[1,] 21   24   27  
[2,] 22   25   28  
[3,] 23   26   29

In [ ]:
data = c(22,33,44,55,66,77,88,66,77)
numeric_matrix <-matrix(data = data, nrow = 3, ncol = 3)
numeric_matrix

print(numeric_matrix[2,2])

[,1] [,2] [,3]
[1,] 22   55   88  
[2,] 33   66   66  
[3,] 44   77   77

[1] 66


In [ ]:
#Date: 11/03/25

#List

data = list(name="Sahil", age="22",height="5.3",subject=c("c++","java","python","sql"))
data

$name
[1] "Sahil"

$age
[1] "22"

$height
[1] "5.3"

$subject
[1] "c++"    "java"   "python" "sql"

In [ ]:
# access data
data$name
data$subject

[1] "Sahil"

[1] "c++"    "java"   "python" "sql"

In [ ]:
# access 1 subject
data$subject[3]
data$subject[2]

[1] "python"

[1] "java"

In [ ]:
# using index
data[2]
data[3]
data[[4]] [2]
data [[4]][4]

$age
[1] "22"

$height
[1] "5.3"

[1] "java"

[1] "sql"

In [ ]:
#update data
data$age = 25
data

$name
[1] "Sahil"

$age
[1] 25

$height
[1] "5.3"

$subject
[1] "c++"    "java"   "python" "sql"

In [ ]:
# delete data
data$height = NULL
data

$name
[1] "Sahil"

$age
[1] 25

$subject
[1] "c++"    "java"   "python" "sql"

In [ ]:
length(data)
names(data)
str(data)

[1] 3

[1] "name"    "age"     "subject"

List of 3
 $ name   : chr "Sahil"
 $ age    : num 25
 $ subject: chr [1:4] "c++" "java" "python" "sql"


In [ ]:
data_matrix <-matrix(1:12,nrow=3,ncol=4)
data_matrix

my_array<-array(data_matrix, dim = c(3,4,2))    #c(row,col,number of array)
my_array

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

In [ ]:
my_array[15]

my_array[22]

[1] 3

[1] 10

In [ ]:
# Creating a 3-dimensional array with dimension names
data_array <- array(1:24, dim = c(3,4,2),
dimnames = list(c("A","B","C"), c("W","X","Y","Z"), c("M","N")))
data_array

, , M

  W X Y  Z
A 1 4 7 10
B 2 5 8 11
C 3 6 9 12

, , N

   W  X  Y  Z
A 13 16 19 22
B 14 17 20 23
C 15 18 21 24

In [ ]:
dim(data_array)
dimnames(data_array)

[1] 3 4 2

[[1]]
[1] "A" "B" "C"

[[2]]
[1] "W" "X" "Y" "Z"

[[3]]
[1] "M" "N"

In [ ]:
# dataframe

# Creating a data frame
student_data <- data.frame(
Name = c("Abhishek","Ritik","Tejas","David"),
Age = c(25, 22, 24, 23),
Grade = c("A","B","A","C"),
Passed = c(TRUE, TRUE, TRUE, FALSE)
)

print(student_data)

      Name Age Grade Passed
1 Abhishek  25     A   TRUE
2    Ritik  22     B   TRUE
3    Tejas  24     A   TRUE
4    David  23     C  FALSE


In [ ]:
student_data$Name[4]

[1] "David"

In [46]:
# Adding a new column
student_data$City <- c("New York","London","Canada","Kashmir")
print(student_data)

      Name Age Grade Passed     City
1 Abhishek  25     A   TRUE New York
2    Ritik  22     B   TRUE   London
3    Tejas  24     A   TRUE   Canada
4    David  23     C  FALSE  Kashmir


In [51]:
names(student_data)
nrow(student_data)
ncol(student_data)
summary(student_data)

[1] "Name"   "Age"    "Grade"  "Passed" "City"

[1] 4

[1] 5

     Name                Age           Grade             Passed       
 Length:4           Min.   :22.00   Length:4           Mode :logical  
 Class :character   1st Qu.:22.75   Class :character   FALSE:1        
 Mode  :character   Median :23.50   Mode  :character   TRUE :3        
                    Mean   :23.50                                     
                    3rd Qu.:24.25                                     
                    Max.   :25.00                                     
     City          
 Length:4          
 Class :character  
 Mode  :character  
                   
                   
                   